### ISSUE TITLE
NPM Premature close

### ISSUE THREAD

**Issue by natedunn** [paleite/typeface-jetbrains-mono#1]
I am getting a `premature close` error when installing via NPM. No issues on Yarn however.

**Comment by paleite** [comment]
Thanks for opening this issue; I wouldn't have caught this for a while!
Turns out npm doesn't support using GitHub dependencies without a package.json. so I used a workaround. I tested it with both npm and yarn now, so hopefully, you won't experience these problems anymore.

I published a new major version (because of name-changes), so if you upgrade to the latest version, it should work.
